/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   JS — PRINT
   Thèmes impression, palettes couleurs, CSS dynamique
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */


let printTheme='light';
const SECTION_PALETTES_LIGHT=[{bg:'#fff9e6',border:'#d4a500',header:'#ffedb3',text:'#7a5800',chord:'#1a1a1a'},{bg:'#e8f4ff',border:'#2d7ab8',header:'#bee3f8',text:'#1a4a7a',chord:'#1a1a1a'},{bg:'#edfff0',border:'#2a9a4a',header:'#c3f0cc',text:'#1a5a2a',chord:'#1a1a1a'},{bg:'#ffeef8',border:'#b83aaa',header:'#f5c6f0',text:'#6a1a5a',chord:'#1a1a1a'},{bg:'#fff0e8',border:'#c05820',header:'#ffd6b8',text:'#7a2800',chord:'#1a1a1a'},{bg:'#f0edff',border:'#5a3ab8',header:'#d4ccf8',text:'#2a1a7a',chord:'#1a1a1a'},{bg:'#e8fffe',border:'#1a9a8a',header:'#b8f0ec',text:'#0a5a50',chord:'#1a1a1a'},{bg:'#fff4f4',border:'#b82a2a',header:'#ffd0d0',text:'#7a1a1a',chord:'#1a1a1a'}];
const SECTION_PALETTES_DARK=[{bg:'#2a2000',border:'#f0c040',header:'#3a2e00',text:'#ffd060',chord:'#ffffff'},{bg:'#001a30',border:'#4ab0f0',header:'#002040',text:'#7dd3fc',chord:'#ffffff'},{bg:'#001a08',border:'#3aaa5a',header:'#002010',text:'#86efac',chord:'#ffffff'},{bg:'#280020',border:'#d060c8',header:'#350028',text:'#f0a8ec',chord:'#ffffff'},{bg:'#280e00',border:'#e07838',header:'#341200',text:'#fbb060',chord:'#ffffff'},{bg:'#180030',border:'#8060e8',header:'#200038',text:'#c4b5fd',chord:'#ffffff'},{bg:'#001a18',border:'#28c8b0',header:'#002020',text:'#5eead4',chord:'#ffffff'},{bg:'#280000',border:'#e04040',header:'#340000',text:'#fca5a5',chord:'#ffffff'}];
function getSectionColorMap(){const palettes=printTheme==='light'?SECTION_PALETTES_LIGHT:SECTION_PALETTES_DARK;const m={};let i=0;chartData.sections.forEach(s=>{const l=s.label||'';if(!(l in m)){m[l]=i%palettes.length;i++;}});return m;}
function buildSectionColorCSS(cl){const palettes=printTheme==='light'?SECTION_PALETTES_LIGHT:SECTION_PALETTES_DARK;const lm=getSectionColorMap();const bBg=printTheme==='dark'?'#111':'white',bC=printTheme==='dark'?'#eee':'black';const bw=[1,1.5,2,2.5,3][cl-1],fs=[1.0,1.05,1.15,1.25,1.35][cl-1];let css=`body{background:${bBg};color:${bC};}#chart-title,#chart-meta input{color:${printTheme==='dark'?'#ffd060':'#1a1a1a'};}`;chartData.sections.forEach((s,si)=>{const p=palettes[lm[s.label||'']];css+=`.section[data-si="${si}"]{background:${p.bg};border:${bw}px solid ${p.border};}.section[data-si="${si}"] .section-header{background:${p.header};}.section[data-si="${si}"] .section-label{color:${p.text};}.section[data-si="${si}"] .measure{background:${printTheme==='dark'?'rgba(255,255,255,0.05)':'rgba(255,255,255,0.7)'};border:${Math.max(1,bw-0.5)}px solid ${p.border}88;}.section[data-si="${si}"] .chord-symbol{color:${p.chord}!important;font-size:${fs}rem;font-weight:${cl>=3?900:700};}.section[data-si="${si}"] .measure-number{color:${p.text}66;}`;});css+='.mode-val{color:#000!important;font-weight:bold!important;font-style:normal!important;}'+'.theory-row-label{color:#333!important;}'+'.arp-val{color:#1a5a8a!important;}'+'.tens-val{color:#1a6a3a!important;}'+'.mode-diagram-wrap svg>text{fill:#000!important;font-weight:bold!important;}'+'.mode-diagram-wrap svg g text{fill:#fff!important;}'+'.mode-diagram-wrap svg line{stroke:#333!important;}'+'.mode-diagram-wrap{background:#fff!important;}';return css;}
function updateSectionColorPreview(){const preview=document.getElementById('section-color-preview');if(!preview)return;preview.innerHTML='';const palettes=printTheme==='light'?SECTION_PALETTES_LIGHT:SECTION_PALETTES_DARK;const lm=getSectionColorMap();Object.entries(lm).forEach(([lbl,idx])=>{const p=palettes[idx];const dot=document.createElement('div');dot.style.cssText=`width:18px;height:18px;border-radius:50%;background:${p.bg};border:2px solid ${p.border};`;dot.title=lbl||'?';preview.appendChild(dot);const span=document.createElement('span');span.style.cssText=`font-size:0.68rem;color:${p.border};margin-right:4px;`;span.textContent=lbl||'?';preview.appendChild(span);});}
function setPrintTheme(theme){printTheme=theme;document.getElementById('theme-light-btn').classList.toggle('on',theme==='light');document.getElementById('theme-dark-btn').classList.toggle('on',theme==='dark');updateSectionColorPreview();}
function openPrintPanel(){document.getElementById('print-contrast-bar').style.display='flex';updateContrastPreview();updateSectionColorPreview();}
function closePrintPanel(){document.getElementById('print-contrast-bar').style.display='none';removePrintStyle();}
function updateContrastPreview(){document.getElementById('contrast-preview').textContent=t('contrastLabels')[parseInt(document.getElementById('contrast-slider').value)-1];}
function injectPrintStyle(v){removePrintStyle();const el=document.createElement('style');el.id='dps';el.media='print';el.textContent=buildSectionColorCSS(v);document.head.appendChild(el);}
function removePrintStyle(){const el=document.getElementById('dps');if(el)el.remove();}
function doPrint(){injectPrintStyle(parseInt(document.getElementById('contrast-slider').value));setTimeout(()=>{window.print();setTimeout(removePrintStyle,1000);},80);}